### ISSUE TITLE
"Failed to load plugin", when trying to enable

### ISSUE THREAD

**Issue by ReaderGuy42** [javalent/second-window#3]
Big fan of the concept! Just found out about your plugin from the newsletter, and installed it via BRAT; but when I go to enable it in the list of Community plugins it tells me that it "failed to load plugin".
I also tried downloading the zip directly and put it in the plugins folder with the same result. 

This occurs both in Legacy mode and the newer one.

I'm on version 0.13.23 (installer version 0.12.15)

Thanks :)

**Comment by valentine195** [comment]
Can you open the developer console (ctrl/shift/i or cmd/option/i) and let me know if there are any errors.

**Comment by ReaderGuy42** [comment]
When I try and enable the plugin, the console says this:
![image](https://user-images.githubusercontent.com/71895400/153726540-5ec00dda-0882-42a0-8fab-49dc86c8d223.png)

**Comment by ReaderGuy42** [comment]
That'd be cool, but no rush, it's the weekend haha :)

**Comment by Galacticminingoperation** [comment]
I'm having this issue too

**Comment by Galacticminingoperation** [comment]
Still having this issue even though it's closed. Don't wanna open a new issue though...

**Comment by valentine195** [comment]
What is your OS, Obsidian version, and Obsidian installer version?

**Comment by qianyingzhuyuan** [comment]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/105531772/212107909-9009961c-c77e-4fb5-824e-826e9462e8b5.png">
I need some help😂😂

**Comment by ReaderGuy42** [comment]
@qianyingzhuyuan not the creator of this plugin, but Excalidraw is an entirely different plugin
