### ISSUE TITLE
"Open in second window" contents are missing

### ISSUE THREAD

**Issue by skerit** [javalent/second-window#40]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

After clicking the button, I expect a window to open with the image

### Current behaviour

The window opens, but it is blank.
There is no HTML in the opened window.

![image](https://github.com/javalent/second-window/assets/755212/d10dda27-6e5b-4052-8585-511698894115)

### Reproduction

1. Run Obsidian v1.5.3 (On Linux)
2. Install "Second Window" 1.1.0
3. Open an image/note using the "Open in second window" choice
4. Window is empty

Opening the same image/note using the built-in "Open in new window" correctly opens a new window (with correct applied styling)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

1.1.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

The main document request fails with the error `No resource with given identifier found`
Request was `app://b822de62b233d97e4e4189cc8fdaaeff54a9/home/skerit/documents/obsidian_vaults/Alia/.obsidian/plugins/image-window/file.html?1703593956837`
The image DOES exist on the filesystem though.

![image](https://github.com/javalent/second-window/assets/755212/f0a9e615-c731-4730-8a00-a86ce9930160)

I thought it might have had something to do with this warning in the console of the new window, about an insecure policy:

```
VM70 sandbox_bundle:2 Electron Security Warning (Insecure Content-Security-Policy):
This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.
```

But when I start up Obsidian with this env variable set:

```
env ELECTRON_DISABLE_SECURITY_WARNINGS=true obsidian
```

The problem is still there (this env variable should disable the CSP, even though it name sounds like it just disables the warnings it would throw :shrug: )

**Comment by luigi-lauro** [comment]
I can confirm this also happen on macOS. 100% a byproduct of latest obsidian release (1.5.x).

**Comment by BurningStarPress** [comment]
I can also confirm that this is happening on MacOS. Everything worked fine prior to the latest Obsidian update.

**Comment by hedonistoic** [comment]
Also happening on Windows

**Comment by DRA6N** [comment]
Can confirm, started happening after the latest Obsidian update.

**Comment by Chr9sG** [comment]
Confirmed on Windows 10 Home also.
